bert_en_path = '/Users/mac/Desktop/ACL22-sarcasm-code/bert-base-uncased/'
# bert_en_path = '/media/dn/newdisk/tools/bert-base-uncased/'
bert_cn_path = '/media/dn/newdisk/tools/chinese_bert/'
root_dataset_dir = './'
# root_dataset_dir = '/media/dn/newdisk/datasets/Self-MM/'
